# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: false

r_binary_packages:
  - devtools
  - tidyverse
  - Rcpp
  - bindrcpp

after_success:
  - Rscript -e 'covr::codecov()'