# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample from the multivariate normal distribution
#'
#' @param n Number of samples to generate.
#' @param mu Center of the distribution.
#' @param sigma Covariance matrix.
#'
#' @return A matrix where each row is a sample.
#' @export
#' @examples
#'
#' mu <- 1:3
#' sigma <- diag(3)
#' rmvn(10, mu, sigma)
#'
rmvn_arma <- function(n, mu, sigma) {
    .Call(`_hayeslib_rmvn_arma`, n, mu, sigma)
}

#' Calculate multivariate normal densities
#'
#' @param x Matrix of multivariate normal samples
#' @param mean Center of the distribution.
#' @param sigma Covariance matrix.
#' @param log Logical indicating if log density should be used.
#'
#' @return Matrix with single column of densities.
#' @export
#'
#' @examples
#'
#' mu <- 1:3
#' sigma <- diag(3)
#' samps <- rmvn(10, mu, sigma)
#' dmvn(samps, mu + 1, sigma)
#'
dmvn_arma <- function(x, mean, sigma, log = FALSE) {
    .Call(`_hayeslib_dmvn_arma`, x, mean, sigma, log)
}

